### ISSUE TITLE
Suggestions for the project

### ISSUE THREAD

**Issue by victormc13** [romans-adi/portfolio-00#4]
### Some suggestions for you:
---
- You could improve the icon resizer and make it a little bigger by trying to do it with a `background-image` for the textarea like this 
![image](https://user-images.githubusercontent.com/110580299/228873038-9aece64a-51fc-43fd-aee7-2c67e0ec3c11.png)
then hide the icon resizer with `display: none` property inside of `textarea::-webkit-resizer `selector like this
![image](https://user-images.githubusercontent.com/110580299/228873793-188576a2-b8a2-4cf9-90e5-44e3a5b55132.png)
and it should work like this
![image](https://user-images.githubusercontent.com/110580299/228874336-d94540ef-998e-47c8-addd-b53172cfe8cf.png)
finally you could change the size of the icon with a `background-size` property if you prefer

Good luck, and happy coding. 😄 👍🏽

**Comment by romans-adi** [comment]
Thank you so much for this! The best solution given. Fixed this part.
